name: qttest
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - ncurses=6.1
  - openssl=1.1.1c
  - pcre=8.43
  - pip=19.1.1
  - pyqt=5.9.2
  - python=2.7.16
  - qt=5.9.7
  - readline=7.0
  - setuptools=41.0.1
  - sip=4.19.8
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - pyyaml==5.1.1
